name: uew_etfs
channels:
  - defaults
dependencies:
  - ca-certificates=2023.01.10
  - openssl=1.1.1t
  - pip=23.0.1
  - python=3.9.16
  - setuptools=66.0.0
  - sqlite=3.41.2
  - vc=14.2
  - vs2015_runtime=14.27.29016
  - wheel=0.38.4
  - pip:
      - anyio==3.7.0
      - appdirs==1.4.4
      - certifi==2023.5.7
      - chardet==3.0.4
      - charset-normalizer==3.1.0
      - datetime==5.1
      - deprecation==2.1.0
      - eikon==1.1.16
      - exceptiongroup==1.1.1
      - h11==0.14.0
      - h2==3.2.0
      - hpack==3.0.0
      - httpcore==0.17.2
      - httpx==0.24.1
      - hyperframe==5.2.0
      - idna==2.10
      - nest-asyncio==1.5.6
      - numpy==1.24.3
      - packaging==23.1
      - pandas==2.0.2
      - python-dateutil==2.8.2
      - pytz==2023.3
      - requests==2.31.0
      - rfc3986==1.5.0
      - six==1.16.0
      - sniffio==1.3.0
      - tzdata==2023.3
      - urllib3==2.0.2
      - websocket-client==1.5.2
      - zope-interface==6.0
